version: '3'

services:
    postgres:
        image: 'postgres:latest'
        restart: always
        volumes:
            - './postgres_data:/var/lib/postgresql/data'
            - './sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql'

        environment:
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5433:5432'
    backend-node:
        build: .
        depends_on:
            - "postgres"
        ports:
            - 8080:8080
        environment:
            - NODE_ENV=development
            - PORT=8080
            - DB_HOST=postgres
            - DB_USER=postgres
            - DB_PWD=postgres
            - DB_NAME=express-crud-example
        command: npm start